### ISSUE TITLE
Publish a release?

### ISSUE THREAD

**Issue by NordicFlyer1** [abhishekbhakat/Xbox360Controller#1]
### Type of Controller
All
### OS Version
macOS 14.0

### Driver Version
NA
### Connection Method
wired

### Device Name and Info
NA

### Response of Controller
NA

### Response in Preference Pane
NA

### Detailed Explaination of Issue

Are you going to publish any releases? Much appreciated - thanks.

**Comment by scueZ** [comment]
Hi @NordicFlyer1, the project is far from release, the internal driver implementation has been changed, and we were actually trying to migrate it to M1, but currently there are plenty of hurdles. So the there is not much of an update here.

**Comment by rhysholland** [comment]
Just wondering if there were any updates on this?

**Comment by abhishekbhakat** [comment]
Nope. Pretty slim chances that we get to work on this.
