### ISSUE TITLE
Feature request: add support for MacOSX14.4(M3Pro)

### ISSUE THREAD

**Issue by lazywhite** [abhishekbhakat/Xbox360Controller#2]
controller:  xbox series s/x
connect method: wired

## Background
As Apple released GPTK, We can play a lot of PC games  by CrossOver, controllers can be connected to mac with Bluetooth, but it has a very large lag due to a lot of campatibility layers(WOW64, Rosetta).  Some game is unplayable like DMC5(can't do back + front + lock + melee attack)  
So we need controller connect mac directly(wired), which will reduce a lot of control lag.   
## Expection
please make this driver work for macosx 14.4 with M chip

**Comment by abhishekbhakat** [comment]
Hey,

The project isn't live. And the documentation was not much helpful 2 years ago. I'm not sure how much has changed until now. We personally haven't found that motivation to keep working on this yet. 

Are you trying a dualshock 4? It would be surprising to see a DS4 have such response times.

**Comment by lazywhite** [comment]
I have no DS4 controller, I think it will have the same problem like xbox,  bluetooth too slow and lack usb driver of mac platform

**Comment by lazywhite** [comment]
I bought a PS5 controller, it has 600HZ bluetooth speed, usb connection is also supported, worked very well with my M3 pro
